/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sudoku.view;

import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author Solkhann
 */
public class MainMenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuPage
     */
    public MainMenuPage() {
        initComponents();
        this.setTitle("NAKudoku - Main Menu");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        levelPromptLabel = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();
        resumeGameButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        levelComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(32, 40, 49));
        jPanel.setForeground(new java.awt.Color(238, 238, 238));
        jPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        titleLabel.setBackground(new java.awt.Color(32, 40, 49));
        titleLabel.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(238, 238, 238));
        titleLabel.setText("<html><center>NAKudoku<br>Nawawi Anabil Kent<br>Sudoku Game</center></html>");

        levelPromptLabel.setBackground(new java.awt.Color(32, 40, 49));
        levelPromptLabel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        levelPromptLabel.setForeground(new java.awt.Color(238, 238, 238));
        levelPromptLabel.setText("Pilih Level :");

        newGameButton.setBackground(new java.awt.Color(238, 238, 238));
        newGameButton.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        newGameButton.setForeground(new java.awt.Color(32, 40, 49));
        newGameButton.setText("New Game");
        newGameButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 173, 181), 2));
        newGameButton.setFocusPainted(false);
        newGameButton.setPreferredSize(new java.awt.Dimension(180, 45));

        resumeGameButton.setBackground(new java.awt.Color(238, 238, 238));
        resumeGameButton.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        resumeGameButton.setForeground(new java.awt.Color(32, 40, 49));
        resumeGameButton.setText("Resume Game");
        resumeGameButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 173, 181), 2));
        resumeGameButton.setFocusPainted(false);
        resumeGameButton.setPreferredSize(new java.awt.Dimension(180, 45));

        historyButton.setBackground(new java.awt.Color(238, 238, 238));
        historyButton.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        historyButton.setForeground(new java.awt.Color(32, 40, 49));
        historyButton.setText("History");
        historyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 173, 181), 2));
        historyButton.setFocusPainted(false);
        historyButton.setPreferredSize(new java.awt.Dimension(180, 45));

        levelComboBox.setBackground(new java.awt.Color(238, 238, 238));
        levelComboBox.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        levelComboBox.setForeground(new java.awt.Color(32, 40, 49));
        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Easy", "Medium", "Hard", "Extreme" }));
        levelComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 173, 181), 2));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resumeGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(levelPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resumeGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuPage().setVisible(true);
            }
        });
    }
    /* Mendapatkan level kesulitan yang dipilih. */
    public String getSelectedDifficulty() {
        return (String) levelComboBox.getSelectedItem();
    }

    /* Mengatur visibilitas tombol Resume Game. */
    public void setResumeButtonVisible(boolean visible) {
        resumeGameButton.setVisible(visible);
    }

    // Metode untuk menambahkan ActionListener ke tombol
    /* Menambahkan ActionListener ke ComboBox level. */
    public void addLevelComboBoxListener(ActionListener listener) {
        levelComboBox.addActionListener(listener);
    }
    /* Menambahkan ActionListener ke tombol New Game. */
    public void addNewGameListener(ActionListener listener) {
        newGameButton.addActionListener(listener);
    }
    /* Menambahkan ActionListener ke tombol Resume Game. */
    public void addResumeGameListener(ActionListener listener) {
        resumeGameButton.addActionListener(listener);
    }
    /* Menambahkan ActionListener ke tombol History. */
    public void addHistoryListener(ActionListener listener) {
        historyButton.addActionListener(listener);
    }

    /* Menampilkan pesan konfirmasi. */
    public boolean showConfirmDialog(String message, String title) {
        int response = JOptionPane.showConfirmDialog(this, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        return response == JOptionPane.YES_OPTION;
    }

    /* Menampilkan pesan informasi. */
    public void showMessageDialog(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton historyButton;
    private javax.swing.JPanel jPanel;
    private javax.swing.JComboBox<String> levelComboBox;
    private javax.swing.JLabel levelPromptLabel;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton resumeGameButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
